---
title: "indexDC"
format: html
---

```{r}

library(tidyverse)
library(sf)
library(data.table)

# load all stops 2010 to June 2024, excluding traffic-involved stops
dcStops23_24 <- read_csv("r-data/dc-stop/Stop_Data.csv") %>% # Stop Data 2023 to June 2024
  filter(TRAFFIC_INVOLVED == 0)

dcStops19_22 <- read_csv("r-data/dc-stop/Stop_Data_2019_to_2022.csv") %>% # Stop Data 2019 to 2022
  filter(TRAFFIC_INVOLVED == 0)

# legacy sqf data
dcStops10_17 <- read_csv("~/Projects/thesis/r-data/dc-stop/Stop_Incidents_2010_to_2017.csv") # Stop Data 2010 to 2017

dcStopsMASTER <- rbindlist(list(dcStops19_22, dcStops23_24), fill = TRUE)

dcDistricts_sf <- read_sf('~/Projects/thesis/r-data/dc-GIS/Police_Districts') # DC MPD Districts 1-7
dcPSA_sf <- read_sf('~/Projects/thesis/r-data/dc-GIS/Police_Service_Areas') # DC MPD Police Service Areas
dcNeighborhood_sf <- read_sf('~/Projects/thesis/r-data/dc-GIS/Neighborhood_Clusters') # DC Government-Designated Neighborhoods
dcBlocks_sf <- read_sf('~/Projects/thesis/r-data/dc-GIS/Census_Blocks_in_2020') # DC 2020 Census Blocks

```

```{r}

# plot the DC district map
dcMAP <- ggplot(dcDistricts_sf) +
  geom_sf(fill = "white", color = "black", linewidth = 0.3) +
  theme_void()

# plot the DC PSA map
dcMAP_PSA <- ggplot(dcPSA_sf) +
  geom_sf(fill = "white", color = "black", linewidth = 0.3) +
  theme_void()

# plot the DC Neighborhood map
dcMAP_hood <- ggplot(dcNeighborhood_sf) +
  geom_sf(fill = "white", color = "black", linewidth = 0.3) +
  theme_void()

# plot the DC 2020 Census Block map
dcMAP_block <- ggplot(dcBlocks_sf) +
  geom_sf(fill = "white", color = "black", linewidth = 0.3) +
  theme_void()

```

```{r}

ggplot(dcPSA_sf) +
  geom_sf(aes(fill = DISTRICT), color = "black", linewidth = 0.3) +
  scale_fill_viridis_c(option = "D") +
  theme_void()

```

```{r tidying location data}

#filtering all stops that do not contain "BLOCK OF" for transformation to address
# note about alternative methods

dcStops19_22 <- dcStops19_22 %>% # 2019 - 2022
  rename(STOP_LOCATION_BLOCK = STOP_LOCATION) %>%
  filter(grepl("BLOCK OF", STOP_LOCATION_BLOCK, ignore.case = TRUE))

dcStops23_24 <- dcStops23_24 %>% # 2023 - 2024
  filter(grepl("BLOCK OF", STOP_LOCATION_BLOCK, ignore.case = TRUE))

# 
```


```{r}

# transform block number to start of block address
dcStops19_22 <- dcStops19_22 %>%
  mutate(
    STOP_LOCATION = str_to_lower(STOP_LOCATION_BLOCK),
    STOP_LOCATION = str_replace_all(STOP_LOCATION, "block of ", ""),
    STOP_LOCATION = str_trim(STOP_LOCATION),
    STOP_LOCATION = str_replace_all(STOP_LOCATION, regex("united states", ignore_case = TRUE), ""),
    STOP_LOCATION = str_trim(STOP_LOCATION),
    STOP_LOCATION = str_replace_all(STOP_LOCATION, regex("dc, washington", ignore_case = TRUE), "washington, dc"),
    STOP_LOCATION = str_replace_all(STOP_LOCATION, regex("dc, dc", ignore_case = TRUE), "washington, dc"),
    STOP_LOCATION = str_replace_all(STOP_LOCATION, regex("dc, wash", ignore_case = TRUE), "washington, dc"),
    STOP_LOCATION = str_trim(STOP_LOCATION)
  )
```

```{r}
library(tidygeocoder)

geo_sample <- dcStops19_22 %>%
  select(GIS_ID, STOP_LOCATION_BLOCK, STOP_LOCATION) %>%
  slice_sample(n = 100000)

write_csv(geo_sample, "geo_sample.csv")

```


```{r}

dcCrimes10_15 <- read_csv("r-data/dc-crime/dc-crimes-2010-2015-results.csv")
dcCrimes16_19 <- read_csv("r-data/dc-crime/dc-crimes-2016-2020-results.csv")
dcCrimes20_24 <- read_csv("r-data/dc-crime/dc-crimes-2020-2024-results.csv")

```

```{r}

# age counts, props, and distribution
age_summary <- dcStopsMASTER %>%
  summarize(
    Mean = round(mean(AGE, na.rm = TRUE), 2),
    Median = median(AGE, na.rm = TRUE),
    Q1 = quantile(AGE, 0.25, na.rm = TRUE),
    Q3 = quantile(AGE, 0.75, na.rm = TRUE),
    Min = min(AGE, na.rm = TRUE),
    Max = max(AGE, na.rm = TRUE),
    "NA" = sum(is.na(AGE))
  )

summarize_counts_props <- function(df, var) {
  df %>%
    count(value = .data[[var]], .drop = FALSE) %>%  # count occurrences, including NA
    mutate(
      prop = round(n / sum(n), 3),
      variable = var
    ) %>%
    select(variable, value, n, prop)
}

# Now apply to each variable:
gender_summary <- summarize_counts_props(dcStopsMASTER, "GENDER")
ethnicity_summary <- summarize_counts_props(dcStopsMASTER, "ETHNICITY")
stop_reason_summary <- summarize_counts_props(dcStopsMASTER, "STOP_REASON_NONTICKET")
stop_type_summary <- summarize_counts_props(dcStopsMASTER, "STOP_TYPE")
stop_district_summary <- summarize_counts_props(dcStopsMASTER, "STOP_DISTRICT")

# Example output:
print(gender_summary)
print(ethnicity_summary)


```

