---
title: "stops"
output: html_document
---

```{r setup, include=FALSE}

if (!exists(".setup_complete") || !.setup_complete) {
      source("setup.R")
    } else {
      message("setup.R has already been run.")
    }

```

```{r quick stop analysis}

# stop breakdown, by race and arrest rate
stopsByRace <- sqf2024 %>% 
  group_by(SUSPECT_RACE_DESCRIPTION) %>%
  count()

# racial proportion of overall stops
stopsByRace <- stopsByRace %>%
  mutate(prop = round(n / sum(n), 2))

# stops by race, including stops that resulted in an arrest
stopsByRaceArrests <- sqf2024 %>% 
  group_by(SUSPECT_RACE_DESCRIPTION, SUSPECT_ARRESTED_FLAG) %>%
  count() %>%
  ungroup(SUSPECT_RACE_DESCRIPTION)

# proportion of overall stops that result in arrest, by race
stopsByRaceArrests <- stopsByRaceArrests %>%
  mutate(prop = round(n / sum(n), 2))


```

```{r stop analysis, by boro}

# stop breakdown, by race and boro
stopsByBoro <- sqf2024 %>% 
  group_by(SUSPECT_RACE_DESCRIPTION, STOP_LOCATION_BORO_NAME) %>%
  count() %>%
  ungroup(STOP_LOCATION_BORO_NAME)

# proportion of overall stops in each boro, by race
stopsByBoro <- stopsByBoro %>%
  mutate(prop = round(n / sum(n), 2))


```


```{r mapping stops to nyc map}

# convert coordinates from sqf data to sf object
stops2024_sf <- sqf2024 %>%
  drop_na(STOP_LOCATION_X, STOP_LOCATION_Y) %>%
  st_as_sf(coords = c("STOP_LOCATION_X", "STOP_LOCATION_Y"), crs = 2263) %>%
  st_transform(crs = 4326)

# dot stop map
nycMAP <- ggplot(nyc_sf) +
  geom_sf(fill = "white", color = "black", linewidth = 0.3) +
  geom_sf(
    data = stops2024_sf,
    aes(geometry = geometry, color = SUSPECT_RACE_DESCRIPTION),
    size = 0.25,
    alpha = 0.4) +         
  coord_sf(xlim = c(-74.3, -73.65), ylim = c(40.48, 40.95)) +
  theme_void() +
  scale_color_viridis_d(option = "B") +
  labs(color = "Suspect Race or Ethnicity") +
  theme(
    legend.key = element_rect(fill = NA, color = NA), legend.key.size = unit(0.5, "cm"),                        
    legend.title = element_text(size = 8), legend.text = element_text(size = 7),                     
    legend.spacing.y = unit(0.2, "cm"), legend.box.spacing = unit(0.3, "cm")                      
  ) +
  guides(color = guide_legend(override.aes = list(shape = 15, size = 4)))
```

```{r heat map of black NYC residents, by nypd precinct}

# join census data to spatial precinct data
nypd_sf <- nypd_sf %>%
  left_join(nypdCensus2020Black, by = c("Precinct" = "precinct"))

# plot heatmap of proportion Black, by precinct
blackHeatMap <- ggplot(nypd_sf) +
  geom_sf(aes(fill = prop), color = "white", linewidth = 0.3) +
  scale_fill_viridis_c(
    option = "rocket",
    name = "Proportion of Black Residents",
    labels = scales::label_percent(accuracy = 1),
    na.value = "gray90"
  ) +
  theme_void() +
  labs(title = "Proportion of Black NYC Residents, by NYPD Precinct")
print(blackHeatMap)

```

```{r heat map of black stops, by nypd precinct}

# census (only one race totals and total 2+ races)
sqf2024raceTotals <- sqf2024 %>%
  select(STOP_ID, STOP_LOCATION_PRECINCT, SUSPECT_RACE_DESCRIPTION) %>%
  group_by(STOP_LOCATION_PRECINCT) %>%
  count(SUSPECT_RACE_DESCRIPTION)

# precincts, proportion of black residents
sqf2024raceTotals <- sqf2024raceTotals %>%
  mutate(prop = round(n / sum(n), 2))

# filter to only include black stops
sqf2024raceBlack <- sqf2024raceTotals %>%
  filter(SUSPECT_RACE_DESCRIPTION == "BLACK")

# join census data to spatial precinct data
nypd_sf <- nypd_sf %>%
  rename(popPropBlack = prop) %>%
  left_join(sqf2024raceBlack, by = c("Precinct" = "STOP_LOCATION_PRECINCT")) %>%
  rename(stopPropBlack = prop)

# plot heatmap of proportion Black stops, by precinct
blackStopHeatMap <- ggplot(nypd_sf) +
  geom_sf(aes(fill = stopPropBlack), color = "white", linewidth = 0.3) +
  scale_fill_viridis_c(
    option = "rocket",
    name = "Proportion Black SQFs",
    labels = scales::label_percent(accuracy = 1),
    na.value = "gray90"
  ) +
  theme_void() +
  labs(title = "Proportion of Black NYC Residents, by NYPD Precinct")

print(blackHeatMap)
print(blackStopHeatMap)

```

```{r frisks by race, gender}

# calculate frisks by race
frisksByRace2024 <- sqf2024 %>%
  group_by(FRISKED_FLAG, SUSPECT_SEX, SUSPECT_RACE_DESCRIPTION) %>%
  drop_na(SUSPECT_SEX) %>%
  filter(SUSPECT_RACE_DESCRIPTION %in% c("BLACK", "BLACK HISPANIC", "WHITE HISPANIC", "WHITE")) %>%
  count() %>%
  ungroup() %>%
  mutate(prop = round(n / sum(n), 2))

# create subtotals by race
subtotals <- frisksByRace2024 %>%
  group_by(SUSPECT_SEX, SUSPECT_RACE_DESCRIPTION) %>%
  summarise(n = sum(n), .groups = "drop") %>%
  mutate(FRISKED_FLAG = "Subtotal")

# combine racial subtotals with original frisks table 
frisksByRace2024 <- bind_rows(frisksByRace2024, subtotals) %>%
  arrange(match(FRISKED_FLAG, c("Y", "N", "Subtotal")),
          match(SUSPECT_SEX, c("MALE", "FEMALE")),
          SUSPECT_RACE_DESCRIPTION)

# pivot wider
frisksByRace2024 <- frisksByRace2024 %>%
  mutate(cell = paste0(n, " (", scales::percent(n / sum(n), accuracy = 0.1), " of total stops)")) %>%
  select(FRISKED_FLAG, SUSPECT_SEX, SUSPECT_RACE_DESCRIPTION, cell) %>%
  pivot_wider(names_from = c(SUSPECT_RACE_DESCRIPTION, SUSPECT_SEX), values_from = cell)
frisksByRace2024

```

```{r searches by race, gender}

# calculate searches by race
searchesByRace2024 <- sqf2024 %>%
  group_by(SEARCHED_FLAG, SUSPECT_SEX, SUSPECT_RACE_DESCRIPTION) %>%
  drop_na(SUSPECT_SEX) %>%
  filter(SUSPECT_RACE_DESCRIPTION %in% c("BLACK", "BLACK HISPANIC", "WHITE HISPANIC", "WHITE")) %>%
  count() %>%
  ungroup() %>%
  mutate(prop = round(n / sum(n), 2))

# pivot wider
searchesByRace2024 <- searchesByRace2024 %>%
  arrange(match(SEARCHED_FLAG, c("Y", "N")),
          match(SUSPECT_SEX, c("MALE", "FEMALE"))) %>%
  mutate(cell = paste0(n, " (", scales::percent(n / sum(n), accuracy = 0.1), " of total stops)")) %>%
  select(SEARCHED_FLAG, SUSPECT_SEX, SUSPECT_RACE_DESCRIPTION, cell) %>%
  pivot_wider(names_from = c(SUSPECT_RACE_DESCRIPTION, SUSPECT_SEX),
              values_from = cell)

```

```{r frisks and searches by race tables}

frisksByRace2024
searchesByRace2024

```

```{r suspect demeanor description sentiment analysis}

library(tidytext)
library(textdata)

# unnest demeanor description, such that the sentiment analysis can work
# https://juliasilge.github.io/tidytext/reference/unnest_tokens.html
# need to figure out a way to make sure the token that's selected isn't erroneous (i.e. "officer", "and", "to", etc.)
stopDemeanorDesc2024 <- sqf2024 %>%
  select(STOP_ID, SUSPECT_RACE_DESCRIPTION, SUSPECT_SEX, DEMEANOR_OF_PERSON_STOPPED, FRISKED_FLAG, SEARCHED_FLAG) %>%
  unnest_tokens(DEMEANOR, DEMEANOR_OF_PERSON_STOPPED, token = "words")

# get sentiments from AFINN datasets
# The AFINN lexicon assigns words with a score that runs between -5 and 5, with negative scores indicating negative sentiment and positive scores indicating positive sentiment.

# calculate sentiment score of officer's description of subject's demeanor for each sto
stopDemeanorSentiment <- stopDemeanorDesc2024 %>%
  full_join(get_sentiments("afinn"), join_by(DEMEANOR == word)) %>% # parse through sentiment data set to find and token
  group_by(SUSPECT_RACE_DESCRIPTION) %>% # group by race
  drop_na(value) %>% # drop observations with no sentiment score
  summarize(mean = round(mean(value), 3)) # get mean score for each racial group

```

```{r custom glimpse}

custom_glimpse <- function(df) {
  data.frame(
    col_name = colnames(df),
    col_index = 1:ncol(df),
    col_class = sapply(df, class),
    row.names = NULL
  )
}

SQFvariables <- custom_glimpse(sqf2024)

```

```{r use of force}

# group all of the types of forces together
weaponForces <- c("PHYSICAL_FORCE_CEW_FLAG", "PHYSICAL_FORCE_DRAW_POINT_FIREARM_FLAG", "PHYSICAL_FORCE_OC_SPRAY_USED_FLAG", "PHYSICAL_FORCE_WEAPON_IMPACT_FLAG")

handcuffForce <- sqf2024 %>%
  mutate(PHYSICAL_FORCE_HANDCUFF_SUSPECT_FLAG = recode(PHYSICAL_FORCE_HANDCUFF_SUSPECT_FLAG,
                                                       "Y" = TRUE,
                                                       "N" = FALSE,
                                                       .default = NA)) %>%
  summarize(
    count_handcuffForce = sum(PHYSICAL_FORCE_HANDCUFF_SUSPECT_FLAG == TRUE, na.rm = TRUE),
    percent_handcuffForce = round(mean(PHYSICAL_FORCE_HANDCUFF_SUSPECT_FLAG == TRUE, na.rm = TRUE), 3)
  )

# otherForce <- c()

forces <- c("PHYSICAL_FORCE_CEW_FLAG", "PHYSICAL_FORCE_DRAW_POINT_FIREARM_FLAG", "PHYSICAL_FORCE_HANDCUFF_SUSPECT_FLAG", "PHYSICAL_FORCE_OC_SPRAY_USED_FLAG", "PHYSICAL_FORCE_OTHER_FLAG", "PHYSICAL_FORCE_RESTRAINT_USED_FLAG", "PHYSICAL_FORCE_VERBAL_INSTRUCTION_FLAG", "PHYSICAL_FORCE_WEAPON_IMPACT_FLAG")

# create a new variable FORCE_FLAG if at least one FORCE variable is not (NULL)
forceByRace2024 <- sqf2024 %>%
  filter(SUSPECT_RACE_DESCRIPTION %in% c("BLACK", "BLACK HISPANIC", "WHITE HISPANIC", "WHITE")) %>%
  mutate(FORCE_FLAG = if_any(all_of(forces), ~ !is.na(.) & . != "(null)"),
         FORCE_WEAPON_FLAG = if_any(all_of(weaponForces), ~ !is.na(.) & . != "(null)"),
         PHYSICAL_FORCE_OTHER_FLAG = recode(PHYSICAL_FORCE_OTHER_FLAG,
                                                       "Y" = TRUE,
                                                       "N" = FALSE,
                                                       .default = NA)
         )

# calculate counts and proportions of use of force
forceByRaceTotals2024 <- forceByRace2024 %>%
  group_by(SUSPECT_RACE_DESCRIPTION, FORCE_FLAG, FORCE_WEAPON_FLAG, PHYSICAL_FORCE_HANDCUFF_SUSPECT_FLAG, PHYSICAL_FORCE_OTHER_FLAG) %>%
  count() %>%
  ungroup() %>%
  mutate(prop = round(n / sum(n), 3),
         cell = paste0(n, " (", prop, ")"))

forceByRaceTable2024 <- forceByRaceTotals2024 %>%
  select(FORCE_FLAG, FORCE_WEAPON_FLAG, PHYSICAL_FORCE_HANDCUFF_SUSPECT_FLAG,
         PHYSICAL_FORCE_OTHER_FLAG, SUSPECT_RACE_DESCRIPTION, cell) %>%
  pivot_wider(
    names_from = SUSPECT_RACE_DESCRIPTION,
    values_from = cell,
    id_cols = c(FORCE_FLAG, FORCE_WEAPON_FLAG, PHYSICAL_FORCE_HANDCUFF_SUSPECT_FLAG, PHYSICAL_FORCE_OTHER_FLAG)
  )


```

```{r encounter-level variables}

sqf2024summary <- sqf2024 %>%
  summarize(
    # count/percent male
    count_male = sum(SUSPECT_SEX == "MALE", na.rm = TRUE),
    percent_male = round(mean(SUSPECT_SEX == "MALE", na.rm = TRUE), 3),
    
    # count/percent male
    count_black = sum(SUSPECT_RACE_DESCRIPTION == "BLACK", na.rm = TRUE),
    percent_black = round(mean(SUSPECT_RACE_DESCRIPTION == "BLACK", na.rm = TRUE), 3),
    
    # count/percent hispanic
    count_hispanic = sum(SUSPECT_RACE_DESCRIPTION %in% c("BLACK HISPANIC", "WHITE HISPANIC"), na.rm = TRUE),
    percent_hispanic = round(mean(SUSPECT_RACE_DESCRIPTION %in% c("BLACK HISPANIC", "WHITE HISPANIC"), na.rm = TRUE), 3),

    # avg age
    avg_age = round(mean(SUSPECT_REPORTED_AGE, na.rm = TRUE), 1),

    # avg weight
    avg_weight = round(mean(SUSPECT_WEIGHT, na.rm = TRUE), 1),

    # avg height
#    avg_height = round(mean(SUSPECT_HEIGHT, na.rm = TRUE), 1),

    # count/percent multiple people stopped
    count_multi = sum(OTHER_PERSON_STOPPED_FLAG == "Y", na.rm = TRUE),
    percent_multi = round(mean(OTHER_PERSON_STOPPED_FLAG == "Y", na.rm = TRUE), 3),

    # count/percent suspect arrested
    count_arrested = sum(SUSPECT_ARRESTED_FLAG == "Y", na.rm = TRUE),
    percent_arrested = round(mean(SUSPECT_ARRESTED_FLAG == "Y", na.rm = TRUE), 3),
    
    # count/percent casing victim/location
    count_casing = sum(SUSPECTS_ACTIONS_CASING_FLAG == "Y", na.rm = TRUE),
    percent_casing = round(mean(SUSPECTS_ACTIONS_CASING_FLAG == "Y", na.rm = TRUE), 3),
    
    # count/percent carried weapon
    count_weapon = sum(BACKROUND_CIRCUMSTANCES_SUSPECT_KNOWN_TO_CARRY_WEAPON_FLAG == "Y", na.rm = TRUE),
    percent_weapon = round(mean(BACKROUND_CIRCUMSTANCES_SUSPECT_KNOWN_TO_CARRY_WEAPON_FLAG == "Y", na.rm = TRUE), 3),
    
    # count/percent concealed weapon
    count_concealed = sum(SUSPECTS_ACTIONS_CONCEALED_POSSESSION_WEAPON_FLAG == "Y", na.rm = TRUE),
    percent_concealed = round(mean(SUSPECTS_ACTIONS_CONCEALED_POSSESSION_WEAPON_FLAG == "Y", na.rm = TRUE), 3),
    
    # count/percent drug transaction
    count_drug = sum(SUSPECTS_ACTIONS_DRUG_TRANSACTIONS_FLAG == "Y", na.rm = TRUE),
    percent_drug = round(mean(SUSPECTS_ACTIONS_DRUG_TRANSACTIONS_FLAG == "Y", na.rm = TRUE), 3),
    
    # count/percent criminal conduct
    count_criminal = sum(SUSPECTS_ACTIONS_IDENTIFY_CRIME_PATTERN_FLAG == "Y", na.rm = TRUE),
    percent_criminal = round(mean(SUSPECTS_ACTIONS_IDENTIFY_CRIME_PATTERN_FLAG == "Y", na.rm = TRUE), 3),
    
    # count/percent lookout
    count_lookout = sum(SUSPECTS_ACTIONS_LOOKOUT_FLAG == "Y", na.rm = TRUE),
    percent_lookout = round(mean(SUSPECTS_ACTIONS_LOOKOUT_FLAG == "Y", na.rm = TRUE), 3),
    
    # count/percent near crime 
    count_nearCrime = sum(SUSPECTS_ACTIONS_PROXIMITY_TO_SCENE_FLAG == "Y", na.rm = TRUE),
    percent_nearCrime = round(mean(SUSPECTS_ACTIONS_PROXIMITY_TO_SCENE_FLAG == "Y", na.rm = TRUE), 3),
    
    # stop initiation
    
        # count/percent officer initiation
        count_officerInitiated = sum(STOP_WAS_INITIATED == "Based on Self Initiated", na.rm = TRUE),
        percent_officerInitiated = round(mean(STOP_WAS_INITIATED == "Based on Self Initiated", na.rm = TRUE), 3),
        
        # count/percent dispatch initiation
        count_dispatchInitiated = sum(STOP_WAS_INITIATED == "Based on Radio Run", na.rm = TRUE),
        percent_dispatchInitiated = round(mean(STOP_WAS_INITIATED == "Based on Radio Run", na.rm = TRUE), 3), 
    
        # count/percent c/w on scene
        count_cwInitiated = sum(STOP_WAS_INITIATED == "Based on C/W on Scene", na.rm = TRUE),
        percent_cwInitiated = round(mean(STOP_WAS_INITIATED == "Based on C/W on Scene", na.rm = TRUE), 3),
  ) %>%
  pivot_longer(
    cols = everything(),
    names_to = c("type", "metric"),
    names_sep = "_",
    values_to = "value"
  ) %>%
  pivot_wider(
    names_from = type,
    values_from = value
  )

sqf2024summary %>%
kbl(caption = "Descriptive Statistics, Stop-and-Frisk 2024 (N = 24,395") %>%
  kable_classic("striped", full_width = F, html_font = "Cambria")


```

```{r precinct-level variables}

# average population of each precinct
avgPop = nypdCensus2020Races %>%
  summarize(avg = round(mean(P1_001N), 0))

# average percent black of each precinct
pctBlack = nypdCensus2020Races %>%
  summarize(avg = round(mean(P1_004N/P1_001N), 4))

# average percent hispanic of each precinct
pctHispanic = nypdCensus2020Races %>%
  summarize(avg = round(mean(P2_002N/P1_001N), 4))

```

```{r}

# Calculate disparity
nypd_sf$stopDisparity <- nypd_sf$propStops - nypd_sf$propPopBlack

# Fit linear model
model <- lm(propStops ~ propPopBlack, data = nypd_sf)
r2 <- summary(model)$r.squared
r2_label <- paste0("R² = ", round(r2, 3))

# Create plot
ggplot(nypd_sf, aes(x = propPopBlack, y = propStops)) +
  geom_point(aes(size = totalStops, color = stopDisparity)) +
  geom_abline(slope = 1, intercept = 0, linetype = "dashed", color = "gray") +
  geom_smooth(method = "lm", se = FALSE, color = "black", linetype = "dotted") +
  annotate("text", x = 0.05, y = max(nypd_sf$propStops), label = r2_label, hjust = 0, size = 4) +
  scale_color_gradient2(low = "green", mid = "green", high = "red", midpoint = 0) +
  labs(
    title = "Proportion of Black Stops vs. Black Population",
    x = "Proportion of Black Population",
    y = "Proportion of Stops Involving Black Individuals",
    color = "Disparity",
    size = "Total Stops"
  ) +
  theme_minimal()


ggplot(nypd_sf) +
  geom_sf(aes(fill = stopDisparity)) +
  scale_fill_viridis_c() +
  labs(
    title = "Geographic Distribution of Stop Disparity",
    fill = "Stop Disparity"
  ) +
  theme_minimal()

```

