---
title: "dea"
format: html
---

```{r setup, include=FALSE}

# check to see if the setup has already been run, if not, run it
# this includes the NYPD crime and SQF data and R libraries 
if (!exists(".setup_complete") || !.setup_complete) {
      source("setup.R")
    } else {
      message("setup.R has already been run.")
    }

# check to see if the GIS setup has already been run, if not, run it
if (!exists(".setup_complete_gis") || !.setup_complete_gis) {
      source("gis.R")
    } else {
      message("gis.R has already been run.")
    }

# check to see if the Census setup has already been run, if not, run it
# `census.R` depends on `gis.R` being run first
if (!exists(".setup_complete_census") || !.setup_complete_census) {
      source("census.R")
    } else {
      message("census.R has already been run.")
    }

```


```{r}

# load deaR
library(deaR)


# import a Dataset
# deaR provides built-in datasets for testing. For example:
data("Fortune500")
head(Fortune500)

# define DEA data
data_dea <- make_deadata(Fortune500, ni = 3, no = 2)

# run a basic dea model (CCR)
model <- model_basic(data_dea, rts = "crs", orientation = "io")
summary(model)

efficiencies(model)


```


```{r}

sqf_hist %>%
  select(STOP_FRISK_ID, STOP_FRISK_DATE, YEAR2, STOP_LOCATION_BORO_NAME, STOP_LOCATION_PRECINCT, 
         FRISKED_FLAG, SEARCHED_FLAG, SUSPECT_ARRESTED_FLAG,
         SUSPECT_RACE_DESCRIPTION, SUSPECT_SEX)


make_deadata(sqf_hist, ni = 77, no = 4)


```

